# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    security.access.museum_voter:
        class:      AppBundle\Security\Voter\MuseumVoter
        public:     false
        tags:
           - { name: security.voter }
